### ISSUE TITLE
NO any Output

### ISSUE THREAD

**Issue by Mr-Kips** [The-Madman-Reborn/Crack-world#1]
when execute , script terminates without showing any error or output.
all the requirements are satisfied 
I also had python2.7.? as well as python3.8.8
it does noting.
(A code that prints Nothing LOL!)

**Comment by Tech-abm** [comment]
Bro again try
Check again my command 
When you run this command on run first remove the symbol 
> pkg update
> pkg upgrade
> pkg install git
> pkg install python2
> pip2 install requests
> pip2 install mechanize
> pip2 install requests bs4
> git clone https://github.com/The-Madman-Reborn/Crack-world
> cd Crack-world
> python2 cracker.indirect

**Comment by Mr-Kips** [comment]
> Bro again try
> Check again my command
> When you run this command on run termux first remove the symbol
> 
> > pkg update
> > pkg upgrade
> > pkg install git
> > pkg install python2
> > pip2 install requests
> > pip2 install mechanize
> > pip2 install requests bs4
> > git clone https://github.com/The-Madman-Reborn/Crack-world
> > cd Crack-world
> > python2 cracker.indirect

thanks
